Closes #301, #305, and #311
tachiyomiorg/website pull request #320
Opened 2020-08-19 04:11 UTC by Seishirou101

2020-08-19 05:07 UTC, Soitora commented
The "closed #x" needs to be a keyword in front of every and not just the first, also I *think* it needs to be in the description and not the title

Title should preferably state the changes in a summary

2020-08-19 05:20 UTC, Seishirou101 commented
updated title and description

2020-09-02 09:42 UTC, GHOSTBEAR commented on src/help/faq/README.md
> +[<MaterialIcon icon-name="videocam"/> Click for video guide](/help/faq/assets/md_noresults.mp4)
The icon doesn't show due to the attribute being renamed to only `icon` from `icon-name`. The correct way to use **MaterialIcon** would be `<MaterialIcon icon="videocam"/>`

2020-09-02 14:34 UTC, Seishirou101 commented on src/help/faq/README.md
> +[<MaterialIcon icon-name="videocam"/> Click for video guide](/help/faq/assets/md_noresults.mp4)
fixed. hopefully, I got all the references of it after I rebased

2020-09-02 15:24 UTC, GHOSTBEAR commented on src/help/guides/source-migration.md
> +1. Go to <MaterialIcon iconName="more_vert"/> and tap **Migrate**.
There are quite a few **MaterialIcon** tags that use the attribute `iconName` in this file, change these attributes to `icon`. If you build the project locally with `npm run serve` you can see that there are errors in the DevTools console when you visit this guide

2020-09-02 15:38 UTC, Seishirou101 commented on src/help/guides/source-migration.md
> +1. Go to <MaterialIcon iconName="more_vert"/> and tap **Migrate**.
done.

> you can see that there are errors in the DevTools console when you visit this guide

Thanks for this tip. This helped me a lot.

2020-09-02 16:02 UTC, Soitora requested changes

2020-09-02 16:02 UTC, Soitora commented on src/help/guides/source-migration.md
> +1. Go to <MaterialIcon icon="more_vert"/> and tap **Migrate**.
```suggestion
1. Go to <Navigation item="more" /> and tap **Migrate**.
```
Stuff like this (including "Extensions") should be used as a Navigation item, meaning if anything changes in the future you only need to update the main file.

2020-09-02 16:02 UTC, Soitora commented on src/help/guides/source-migration.md
>  [<MaterialIcon icon="videocam"/> Click for video guide](/help/guides/source-migration/assets/migrate_j2k.mp4)
```suggestion
::: aside-guide
[<MaterialIcon icon="videocam"/> Click for video guide](/help/guides/source-migration/assets/migrate_j2k.mp4)
:::
```
These should be as an aside-guide, when including a three-colon object in another though you need to increase the main one, so `::: guide TachiyomiJ2K Migration` becomes `:::: guide TachiyomiJ2K Migration`, including the ending `:::` to `::::`

2020-09-02 16:03 UTC, Soitora commented
Somehow my review added on to my other review (even though it said only 2 reviewed), which caused oddities. Hope you can still see what I mean

2020-09-02 18:04 UTC, Seishirou101 commented on src/help/guides/source-migration.md
> +[<MaterialIcon icon="videocam"/> Click for video guide](/help/guides/source-migration/assets/migrate_preview.mp4)
Will do, thanks

2020-09-02 18:05 UTC, Seishirou101 commented on src/help/guides/source-migration.md
> +1. Go to <MaterialIcon iconName="more_vert"/> and tap **Migrate**.
changed with the addition of the Navigation item overflow.

2020-09-08 19:35 UTC, Seishirou101 commented
need to split videos for changes soi made

2020-09-11 21:09 UTC, Seishirou101 commented
videos have been updated

2020-09-12 16:50 UTC, Soitora commented
I'll accept it for now as it looks fine, if anyone catches anything wrong do make an issue about it or contact either of us.

2020-09-12 16:50 UTC, Soitora approved these changes

2020-09-13 00:43 UTC, merged