Add Preview description
tachiyomiorg/website pull request #429
Opened 2020-10-31 19:28 UTC by scb261

Added Tachiyomi Preview description to https://tachiyomi.org/help/faq/#miscellaneous and linked it from the download page, closes #206

2020-10-31 19:38 UTC, Soitora requested changes

2020-10-31 19:38 UTC, Soitora commented on src/help/faq/README.md
> +It's weekly updated version of the app. It contains features that can be added to Tachiyomi in the future, but there is a higher chance for bugs. Tachiyomi Preview is used by developers and contribut
```suggestion
It's a weekly updated version of the app. It contains features that can be added to Tachiyomi in the future, but there is a higher chance for bugs. Tachiyomi Preview is used by developers and contributors to test the app and find bugs.

If you are willing to use Tachiyomi Preview, be sure [turn on auto-backup](/help/guides/creating-backups/#turning-on-auto-backups) to prevent losing your library due to potential bugs.
```

2020-10-31 19:44 UTC, Flat commented on src/help/faq/README.md
> +It's weekly updated version of the app. It contains features that can be added to Tachiyomi in the future, but there is a higher chance for bugs. Tachiyomi Preview is used by developers and contribut
> If you are willing to use Tachiyomi Preview, be sure [turn on auto-backup](/help/guides/creating-backups/#turning-on-auto-backups) to prevent losing your library due to potential bugs.

... be sure **__to__** [turn on auto-backup]...

2020-10-31 20:23 UTC, Soitora commented on src/help/faq/README.md
> +It's weekly updated version of the app. It contains features that can be added to Tachiyomi in the future, but there is a higher chance for bugs. Tachiyomi Preview is used by developers and contribut
What is English for $300

2020-11-01 11:53 UTC, Soitora commented
Maybe should have the "read more about" link set to the download modal instead, it supports HTML:
![image](https://user-images.githubusercontent.com/10836780/97802059-402bdb00-1c41-11eb-9826-c9d3ea0c20cc.png)

2020-11-01 12:48 UTC, scb261 commented
Like this?
![1](https://user-images.githubusercontent.com/65343233/97803117-a4a26680-1c50-11eb-8c77-2ec1855a8d8c.png)

2020-11-02 10:40 UTC, Soitora approved these changes

2020-11-02 10:40 UTC, merged