Create tracking page
tachiyomiorg/website pull request #460
Opened 2020-11-24 09:16 UTC by loocool2

closes #318

2020-11-24 10:12 UTC, ghostbear requested changes

2020-11-24 10:12 UTC, ghostbear commented on src/help/guides/tracking.md
> +Tap the box next to the logo of the tracker to add the manga to the tracker.
Maybe `Tap "Add tracking" to add the manga to the tracker`

2020-11-24 10:12 UTC, ghostbear commented on src/help/guides/tracking.md
> +## Setting up tracking for each entry
Should this not be an ordered list:
```markdown
1. Tap the manga
2. Tap the <MaterialIcon icon="sync" />
3. Tap "Add tracking"
    <ul>
        <li>Optional: You can change the search query</li>
    </ul>
```

2021-01-24 22:15 UTC, ghostbear reviewed
I'm guessing you still have the intent to add images to this pull request?

2021-01-25 17:42 UTC, loocool2 commented
I do

2021-01-29 16:26 UTC, ghostbear commented on src/help/guides/tracking.md
> +
You probably want to close the gudie as well
```suggestion
:::: guide Guide
::: videolink
[<MaterialIcon icon="videocam"/> Click for video guide](/assets/guides_login-to-tracker.mp4)
:::

1. Goto More → Settings → Tracking to Login
2. Tap the tracker you would like to login to, it will automatically open the browser and lead you through the login process.
::::
```

2021-01-29 16:26 UTC, ghostbear commented on src/help/guides/tracking.md
> +    </ul>
Same here, you probably want to close the gudie as well
```suggestion
:::: guide Guide
::: videolink
[<MaterialIcon icon="videocam"/> Click for video guide](/assets/guides_add-to-tracker.mp4)
:::

1. Tap the manga
2. Tap the <MaterialIcon icon="sync" />
3. Tap "Add tracking" to add the manga to the tracker
    <ul>
        <li>Optional: You can change the search query</li>
    </ul>
::::
```

2021-01-29 16:26 UTC, ghostbear commented on src/help/guides/tracking.md
> +title: Tracking titles
```suggestion
title: Tracking manga
```

2021-01-29 16:42 UTC, ghostbear commented
You sure you don't wanna just name the guides `Guide` instead of `Video Guide`?
![image](https://user-images.githubusercontent.com/6576096/106302436-44c05980-6259-11eb-85fb-a3981df9aecc.png)

2021-01-29 16:43 UTC, loocool2 commented
How did I miss that 🤔

2021-01-29 16:56 UTC, ghostbear approved these changes
LGTM 👍

2021-01-29 16:59 UTC, merged