Update FAQ page
tachiyomiorg/website pull request #559
Opened 2021-03-02 23:24 UTC by specterflare

Here is my justification for each change, going top to bottom. 

The "blocking groups/duplicte chapters" is an extension thing, not an application thing, since it varies by extensions. I put a general one under extensions as a whole and specific ones under Mangadex and Mangapark.

Basic grammar fixes.

Removed the MAL search thing since it was fixed with tachiyomiorg/tachiyomi#2042 

Added addition way to fix broken covers, sourced from [this comment](https://github.com/tachiyomiorg/tachiyomi/issues/932#issuecomment-760367005) on the issue thread.

More grammar fixes

Removed a line about Tachiyomi translations not translating manga. People aren't THAT dumb, right?

Even more grammar

Added the possibility of having to add `.nomedia` to your local folder (I did have to once)

Moved "restore from backup" to the Application section where it belongs, and added a line about how restores now warn you if you are missing sources.

Improved description of scanlator sources and removed some recommendations, as it was stated that Tachiyomi does not recommend extensions.

Github formatted this really weirdly, but I added a general "how do I skip duped chapters" and also removed an unnecessary info box beneath the extension redirect since the same info is present on the extension page.

Removed a weird extension install question that, as far as I could tell, didn't say anything? I'm pretty sure there is no way to download the extensions outside of the app. If I am wrong, please correct me.

Removed a question that pertained to Tachi moving away from built-in sources. Since that happened [three years ago](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.7.0) I am sure the number of users needing this information is essentially zero.

As said above, moved "restore" to the application section.

Removed a duplicate of the question on looking up manga. It's kinda weird that there were two, but I kept the one in the application section since it fits better there.

Reworded specific ignore chapter instructions for Mangadex.

Removed Mangabox issues as they are no longer relevant since they split into separate extensions.

So, I looked, and I literally could find no evidence of an extension called Japscan ever existing for Tachiyomi. I removed it, but if I'm just being blind, let me know.

Removed MangaRock thing, it happened a year ago and everyone knows.

Reworded KissManga sentence.

2021-03-03 01:03 UTC, scb261 reviewed
Just my opinions as a support on discord and I'm not sure about some of them. Maybe better wait for someone who actually reviews and approves PRs, so they could say for sure

2021-03-03 01:11 UTC, Seishirou101 commented
pinging @loocool2 too I guess since they're doing a faq rewrite

2021-03-03 09:54 UTC, Soitora commented
When support has looked over this and feels confident it is ready, I can merge it.

2021-03-03 15:48 UTC, specterflare commented on src/help/faq/README.md
> +Sometimes you can struggle to find a source that has the manga you're looking for. Here for some tips to help you find it:
Done

2021-03-03 16:04 UTC, specterflare commented on src/help/faq/README.md
> -
Added them in, thanks

2021-03-03 16:04 UTC, specterflare commented on src/help/faq/README.md
> -
Added them in, thanks

2021-03-03 16:12 UTC, specterflare commented on src/help/faq/README.md
> +1. Check if a specific website or scanlator has the series, then look for them in the [Extensions](/extensions/) list.
Done, thanks

2021-03-03 16:43 UTC, specterflare commented on src/help/faq/README.md
> +The app doesn't allow simultaneous downloads from one source to prevent IP bans caused by too many requests. We know that speed is being sacrificed but it's better than not being able to access a sou
Good point, re-addded

2021-03-03 16:50 UTC, specterflare commented on src/help/faq/README.md
> -
Ok, I added it back. I also reworded it to make it more helpful.

2021-03-03 16:51 UTC, specterflare commented on src/help/faq/README.md
> +#### Why can I see manga pages in my phone's photo library?
Done

2021-03-03 16:57 UTC, scb261 commented on src/help/faq/README.md
> +Manga that are not officially licensed are translated by scanlators, who either publish on their own website or on **MangaDex**. This is in contrast to official sources like **MangaSee** or **MANGA P
You can also add viz here, since it's also official

2021-03-03 17:00 UTC, specterflare commented on src/help/faq/README.md
> -
Ohhhh. I added it back but completely rewrote it to make more sense. Thanks for that, not sure how I missed it.

2021-03-03 17:04 UTC, specterflare commented on src/help/faq/README.md
> +Manga that are not officially licensed are translated by scanlators, who either publish on their own website or on **MangaDex**. This is in contrast to official sources like **MangaSee** or **MANGA P
Thanks, updated

2021-03-03 17:06 UTC, specterflare commented on src/help/faq/README.md
> +In *older* versions of **Android**, you only need to enable **Unknown sources** globally.
Thanks, added second comma

2021-03-03 17:10 UTC, specterflare commented on src/help/faq/README.md
> +Manga that are not officially licensed are translated by scanlators, who either publish on their own website or on **MangaDex**. This is in contrast to official sources like **MangaSee** or **MANGA P
Whoops, missed your most recent comment. Viz is a better example than Toomics, I'll add that in instead.

2021-03-03 17:13 UTC, specterflare commented on src/help/faq/README.md
> -
Done, thanks

2021-03-03 17:17 UTC, scb261 commented on src/help/faq/README.md
> +2. If you still can' find the manga in any of your sources, use the names you found in Step 1 to check if a specific scanlator site or more niche aggregator site has the series, then look for them in
```suggestion
1. Look up the manga on [Google](https://google.com/) or a manga database such as [MangaUpdates](https://www.mangaupdates.com/).
1. See if the manga has any alternate spellings or other title variations. Try searching again in your sources with the alternate titles you found.
1. If you still can't find the manga in any of your sources, then try to search for an extension for the site you've found in step 1 in the [extensions](/extensions/) list.
```

2021-03-03 17:22 UTC, scb261 commented on src/help/faq/README.md
> +Check if adding them as an extension has [already been requested](https://github.com/tachiyomiorg/tachiyomi-extensions/issues). If they haven't been, you can [request it yourself](https://github.com/
```suggestion
Check if adding the site as an extension has [already been requested](https://github.com/tachiyomiorg/tachiyomi-extensions/issues). If it hasn't been, you can [request it yourself](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
```

2021-03-03 17:22 UTC, specterflare commented on src/help/faq/README.md
> -
Re-added and updated, thanks

2021-03-03 17:24 UTC, ghostbear commented on src/help/faq/README.md
> +If the website/scanlator doesn't have an online manga reader, you can download the manga from their site and set up the series as a [local manga](/help/guides/reading-local-manga).
Shouldn't this be 
```suggestion
If the scanlator/aggregator doesn't have an online manga reader, you can download the manga from their site and set up the series as a [local manga](/help/guides/reading-local-manga).
```

2021-03-03 17:28 UTC, specterflare commented on src/help/faq/README.md
> -
Huh, that is weird. I hand-waved it by saying it uses a "a very complicated method of accessing pages".

2021-03-03 17:34 UTC, specterflare commented on src/help/faq/README.md
> +**KissManga** closed permanently in August 2020.
Huh. I added it back and formatted out those weird collapsible things since they were a pain and an extra click for readers. I am under the impression that those should only be used for large stretches of content or optional addtions.

2021-03-03 17:36 UTC, specterflare commented on src/help/faq/README.md
> +
I removed it, we can decide if we want to re-add it later.

2021-03-03 17:39 UTC, specterflare commented
I changed "phone" to "device", since some people (like me!) use an android tablet.

2021-03-03 17:40 UTC, ghostbear commented on src/help/faq/README.md
> +Be aware that it could be a network issue on your device or on the site you are trying to download from.
Maybe use `website` because `site` means multiple things, which may be confusing to non-native English speakers 
```suggestion
Be aware that it could be a network issue on your device or on the website you are trying to download from.
```

2021-03-03 17:51 UTC, specterflare commented on src/help/faq/README.md
> +1. Migrate to another source that does not have duplicates. For more information on how to migrate a manga, see the [guide](/help/guides/source-migration/).
Done, thanks

2021-03-03 17:56 UTC, specterflare commented on src/help/faq/README.md
> +2. If you still can' find the manga in any of your sources, use the names you found in Step 1 to check if a specific scanlator site or more niche aggregator site has the series, then look for them in
Updated, thanks

2021-03-03 17:56 UTC, specterflare commented on src/help/faq/README.md
> +Check if adding them as an extension has [already been requested](https://github.com/tachiyomiorg/tachiyomi-extensions/issues). If they haven't been, you can [request it yourself](https://github.com/
Updated, thanks

2021-03-03 17:57 UTC, specterflare commented on src/help/faq/README.md
> +If the website/scanlator doesn't have an online manga reader, you can download the manga from their site and set up the series as a [local manga](/help/guides/reading-local-manga).
Updated, thanks

2021-03-03 17:58 UTC, specterflare commented on src/help/faq/README.md
> +Be aware that it could be a network issue on your device or on the site you are trying to download from.
Good catch, thanks

2021-03-03 18:03 UTC, scb261 commented on src/help/faq/README.md
> +* Bookmark or mark as read the unwanted chapters, then click on <Navigation item="filter"/> → **Filter** and double-tap **Bookmarked** or single-tap **Unread**, respectivly. This will hide any bookma
```suggestion
* Bookmark or mark as read the unwanted chapters, then click on <Navigation item="filter"/> → **Filter** and double-tap **Bookmarked** or single-tap **Unread**, respectively. This will hide any bookmarked or read chapters and skip them as you read along, as long as you have **Skip filtered chapters** enabled under <Navigation item="more"/> → <Navigation item="settings"/> → <Navigation item="settings_reader"/> → **Reading**.
```

2021-03-03 18:05 UTC, specterflare commented on src/help/faq/README.md
> +* Bookmark or mark as read the unwanted chapters, then click on <Navigation item="filter"/> → **Filter** and double-tap **Bookmarked** or single-tap **Unread**, respectivly. This will hide any bookma
Oof, not sure how I missed that. Thanks

2021-03-03 18:08 UTC, scb261 commented on src/help/faq/README.md
> +You can go to the manga's page in <Navigation item="webview"/> and block groups you do not want to see. Close <Navigation item="webview"/> and refresh the manga in the app. The group's chapters shoul
```suggestion
You can go to the manga's page in <Navigation item="webview"/> and block groups you do not want to see. Close <Navigation item="webview"/> and refresh the manga in the app. The group's chapters should be gone now.
```

2021-03-03 18:14 UTC, scb261 commented on src/help/faq/README.md
> +This means that the manga is dead and needs to be migrated from **Mangakakalot** or **Manganelo** to a different source. Refer to the [migration guide](/help/guides/source-migration/)
Those manga are actually still on kakalot/nelo/etc but with different url. To fix it, users need to migrate from kakalot/nelo/etc to kakalot/nelo/etc. But along with this we also recommend to migrate to another source at all. Maybe something like `Migrate the manga from kakalot/nelo/etc back to kakalot/nelo/etc, or better yet to another source to avoid similar errors in future`.

Also should either mention all sources or replace them with some general name.

2021-03-03 18:24 UTC, specterflare commented on src/help/faq/README.md
> +You can go to the manga's page in <Navigation item="webview"/> and block groups you do not want to see. Close <Navigation item="webview"/> and refresh the manga in the app. The group's chapters shoul
Done, thanks

2021-03-03 18:28 UTC, Seishirou101 commented on src/help/faq/README.md
> -::: guide
is there a reason you removed the guide here? otherwise, you'll need to remove the ending of it.

2021-03-03 18:28 UTC, Seishirou101 commented on src/help/faq/README.md
> +Certain devices such as MIUI have very aggressive battery saving, which can kill the app in the background. To whitelist Tachiyomi from your battery saver, go to <Navigation item="more"/> → <Navigati
we should probably mention https://dontkillmyapp.com/ as most aggressive battery saving devices need a lot more than just this setting.

2021-03-03 18:28 UTC, Seishirou101 commented on src/help/faq/README.md
> +To restore backups, **Tachiyomi** requires to have extensions installed for the respective manga you want to restore. The app should warn you if you attempt to restore a backup without having the nec
This is not completely true anymore due to the new backup system, so may need to change it or just link to /help/guides/creating-backups/#restoring

2021-03-03 18:30 UTC, specterflare commented on src/help/faq/README.md
> +This means that the manga is dead and needs to be migrated from **Mangakakalot** or **Manganelo** to a different source. Refer to the [migration guide](/help/guides/source-migration/)
I updated the information and consolidated the first two errors, thanks.

2021-03-03 18:32 UTC, specterflare commented on src/help/faq/README.md
> -::: guide
No, that was a mistake, good catch.

2021-03-03 18:41 UTC, specterflare commented on src/help/faq/README.md
> +Certain devices such as MIUI have very aggressive battery saving, which can kill the app in the background. To whitelist Tachiyomi from your battery saver, go to <Navigation item="more"/> → <Navigati
Added, thanks

2021-03-03 18:44 UTC, ghostbear commented on src/help/faq/README.md
> +1. If you still can't find the manga in any of your sources, then try to search for an extension for the site you've found in step 1 in the [extensions](/extensions/) list.
```suggestion
1. If you still can't find the manga in any of your sources, then try to search for an extension for the website you've found in step 1 in the [extensions](/extensions/) list.
```

2021-03-03 18:44 UTC, ghostbear commented on src/help/faq/README.md
> +Check if adding the site as an extension has [already been requested](https://github.com/tachiyomiorg/tachiyomi-extensions/issues). If it hasn't been, you can [request it yourself](https://github.com
I think you could probably omit (web)site here
```suggestion
#### If you find the manga on a specific scanlator/aggregator and they do have an extension
Download the corresponding extension, click on it under <Navigation item="browse"/> → **Sources**, and then search for the manga there.
#### If you find the manga on a specific scanlator/aggregator and they don't have an extension
Check if adding the site as an extension has [already been requested](https://github.com/tachiyomiorg/tachiyomi-extensions/issues). If it hasn't been, you can [request it yourself](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
```
or 
```suggestion
#### If you find the manga on a specific scanlator/aggregator website and they do have an extension
Download the corresponding extension, click on it under <Navigation item="browse"/> → **Sources**, and then search for the manga there.
#### If you find the manga on a specific scanlator/aggregator website and they don't have an extension
Check if adding the site as an extension has [already been requested](https://github.com/tachiyomiorg/tachiyomi-extensions/issues). If it hasn't been, you can [request it yourself](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
```

2021-03-03 18:44 UTC, ghostbear commented on src/help/faq/README.md
> +If the scanlator/aggregator doesn't have an online manga reader, you can download the manga from their site and set up the series as a [local manga](/help/guides/reading-local-manga).
```suggestion
If the scanlator/aggregator doesn't have an online manga reader, you can download the manga from their website and set up the series as a [local manga](/help/guides/reading-local-manga).
```

2021-03-03 18:44 UTC, ghostbear commented on src/help/faq/README.md
> +Due to Google Play's content policy, almost certainly not, as they do not allow the APK system to work. The content on some sites will lead to Google taking it down at some point, and Inorichi does n
```suggestion
Due to Google Play's content policy, almost certainly not, as they do not allow the APK system to work. The content on some websites will lead to Google taking it down at some point, and Inorichi does not want to have to deal with it as they have stated [before](https://github.com/tachiyomiorg/tachiyomi/issues/1745#issuecomment-441208074).
```

2021-03-03 18:44 UTC, ghostbear commented on src/help/faq/README.md
> +The former **Mangabox** extensions have created new entries for many of the manga on their sites. The old entries are obsolete and will not work. To resolve this, [migrate](/help/guides/source-migrat
```suggestion
The former **Mangabox** extensions have created new entries for many of the manga on their websites. The old entries are obsolete and will not work. To resolve this, [migrate](/help/guides/source-migration/) the manga from the source to itself in order to get the new entry, or better yet to a different source entirely to avoid similar errors in the future.
```

2021-03-03 18:44 UTC, ghostbear commented on src/help/faq/README.md
>  You will have to open the manga entry in WebView and verify your age, as Webtoons has recently added age verifications on their site.
```suggestion
You will have to open the manga entry in WebView and verify your age, as Webtoons has recently added age verifications on their website.
```

2021-03-03 18:53 UTC, specterflare commented on src/help/faq/README.md
> +To restore backups, **Tachiyomi** requires to have extensions installed for the respective manga you want to restore. The app should warn you if you attempt to restore a backup without having the nec
Was feeling lazy, just linked to the guide

2021-03-03 18:54 UTC, specterflare commented on src/help/faq/README.md
> +1. If you still can't find the manga in any of your sources, then try to search for an extension for the site you've found in step 1 in the [extensions](/extensions/) list.
Done, thanks

2021-03-03 18:55 UTC, specterflare commented on src/help/faq/README.md
> +Check if adding the site as an extension has [already been requested](https://github.com/tachiyomiorg/tachiyomi-extensions/issues). If it hasn't been, you can [request it yourself](https://github.com
Done, thanks

2021-03-03 18:56 UTC, specterflare commented on src/help/faq/README.md
> +If the scanlator/aggregator doesn't have an online manga reader, you can download the manga from their site and set up the series as a [local manga](/help/guides/reading-local-manga).
Done, thanks

2021-03-03 18:56 UTC, specterflare commented on src/help/faq/README.md
> +Due to Google Play's content policy, almost certainly not, as they do not allow the APK system to work. The content on some sites will lead to Google taking it down at some point, and Inorichi does n
Done, thanks

2021-03-03 18:57 UTC, specterflare commented on src/help/faq/README.md
> +The former **Mangabox** extensions have created new entries for many of the manga on their sites. The old entries are obsolete and will not work. To resolve this, [migrate](/help/guides/source-migrat
Done, thanks

2021-03-03 18:58 UTC, specterflare commented on src/help/faq/README.md
>  You will have to open the manga entry in WebView and verify your age, as Webtoons has recently added age verifications on their site.
Done, thanks

2021-03-03 19:16 UTC, specterflare commented
I changed the header on the mangabox extension help away from listing each extension individually because it looked hella ugly on the sidebar:

Before:
![Screenshot (382)](https://user-images.githubusercontent.com/61708534/109859484-04bf0e80-7c2b-11eb-8750-7abab2c00e12.png)

After:
![Screenshot (380)](https://user-images.githubusercontent.com/61708534/109859497-0983c280-7c2b-11eb-9411-8cbbaa4c872d.png)

2021-03-03 19:19 UTC, specterflare commented
Also, I was going to make this a separate issue report, but since everyone's here: The "Last updated:" on the bottom of each page always says "a minute ago" no matter what on all the pages. I remember it working a couple of months ago. What broke it?

2021-03-03 23:52 UTC, loocool2 requested changes
I'd like for the entire extensions section to be moved at some point but I'm not sure what exactly to do right now

2021-03-03 23:52 UTC, loocool2 commented on src/help/faq/README.md
> +The former **Mangabox** extensions have created new entries for many of the manga on their websites. The old entries are obsolete and will not work. To resolve this, [migrate](/help/guides/source-mig
```suggestion
The former **Mangabox** extensions have created new entries for many of the manga on their websites. The old entries are obsolete and will not work. To resolve this, [migrate](/help/guides/source-migration/) the manga from the source to itself to get the new entry, or better yet, to a different source entirely to avoid similar errors in the future.
```

2021-03-03 23:52 UTC, loocool2 commented on src/help/faq/README.md
> +As part of a general move to split up multi-source extensions, the Mangabox extension was removed, and all of its sources were made into their own extensions, namley **Mangakakalot**, **Manganelo**,
```suggestion
As part of a general move to split up multi-source extensions, the Mangabox extension was removed, and all of its sources were made into their own extensions, namely **Mangakakalot**, **Manganelo**, **Mangabat** and **Mangairo**.
```

2021-03-03 23:52 UTC, loocool2 commented on src/help/faq/README.md
> +The **JapScan** extension uses a very complicated method of accessing pages. If you encounter a manga that does not load or is scrambled, use a different source to read.
You can remove this section if you'd like. Japscan's encryption is so complicated that it's not worth keeping an extension anymore, aside from a janky version that screenshots the pages.

2021-03-03 23:52 UTC, loocool2 commented on src/help/faq/README.md
> +If the scanlator/aggregator doesn't have an online manga reader, you can download the manga from their website and set up the series as a [local manga](/help/guides/reading-local-manga).
```suggestion
If the scanlator or aggregator doesn't have an online manga reader, you can download the manga from their website and set up the series as a [local manga](/help/guides/reading-local-manga).
```

2021-03-04 06:19 UTC, specterflare commented on src/help/faq/README.md
> +The former **Mangabox** extensions have created new entries for many of the manga on their websites. The old entries are obsolete and will not work. To resolve this, [migrate](/help/guides/source-mig
Updated, thanks

2021-03-04 06:19 UTC, specterflare commented on src/help/faq/README.md
> +As part of a general move to split up multi-source extensions, the Mangabox extension was removed, and all of its sources were made into their own extensions, namley **Mangakakalot**, **Manganelo**,
Nice catch, thanks

2021-03-04 06:21 UTC, specterflare commented on src/help/faq/README.md
> +The **JapScan** extension uses a very complicated method of accessing pages. If you encounter a manga that does not load or is scrambled, use a different source to read.
Done, thanks

2021-03-04 06:21 UTC, specterflare commented on src/help/faq/README.md
> +If the scanlator/aggregator doesn't have an online manga reader, you can download the manga from their website and set up the series as a [local manga](/help/guides/reading-local-manga).
Updated, thanks

2021-03-06 02:40 UTC, loocool2 approved these changes
Looks good to me

2021-03-06 10:30 UTC, merged